version: 2

project_name: git-foreach

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild

builds:
  - builder: rust
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    flags:
      - --release
      - --package=git-foreach

checksum:
  name_template: "checksums.txt"

homebrew_casks:
  - name: "{{ .ProjectName }}"
    description: "Utility to recursively run commands in Git repositories."
    repository:
      owner: "marcfrederick"
      name: "homebrew-tap"
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^build(\\(.*\\))?:"
      - "^ci:"
      - "^docs:"
      - "^test:"
