repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        files: '\.rs$'
        entry: mise run fmt
        pass_filenames: false
      - id: clippy
        name: clippy
        language: system
        files: '\.rs$'
        entry: mise run clippy
        pass_filenames: false
      - id: test
        name: test
        language: system
        files: '\.rs$'
        entry: mise run test
        pass_filenames: false
      - id: deny
        name: deny
        language: system
        files: '^(Cargo\.lock|Cargo\.toml|deny\.toml|mise\.toml)$'
        entry: mise run deny
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
