[package]
name = "git-foreach"
description = "Run a command in each git repository in a directory"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
lto = true

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo"] }
ignore = "0.4.22"
