[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
all-features = true

[advisories]
version = 2

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
version = 2
confidence-threshold = 0.99
allow = ["Apache-2.0", "MIT"]

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
crate = "unicode-ident"

